# Generated by Django 5.2.7 on 2025-11-07 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('patient', 'Patient'), ('therapist', 'Therapist'), ('researcher', 'Researcher')], default='', max_length=20)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, default='', max_length=10)),
                ('license_no', models.CharField(blank=True, default='', max_length=100)),
                ('experience', models.PositiveIntegerField(blank=True, null=True)),
                ('specialization', models.CharField(blank=True, default='', max_length=200)),
                ('institution', models.CharField(blank=True, default='', max_length=200)),
                ('research_field', models.CharField(blank=True, default='', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
