# Generated by Django 5.2.7 on 2025-11-16 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vrproapp', '0002_remove_userprofile_age_remove_userprofile_experience_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phobia', models.CharField(choices=[('heights', 'Fear of Heights'), ('spider', 'Fear of Spiders'), ('publicspeaking', 'Public Speaking')], max_length=20)),
                ('severity_now', models.IntegerField(default=5, help_text='How intense is the fear right now (0–10)?')),
                ('main_triggers', models.TextField(blank=True, help_text='Situations or objects that trigger the fear.')),
                ('physical_symptoms', models.TextField(blank=True, help_text='What happens in your body when you face this fear?')),
                ('main_goal', models.TextField(blank=True, help_text='What would you like to be able to do after therapy?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'phobia')},
            },
        ),
    ]
